---
- name: Find public ip
  local_action:
    module: "shell kubectl get services {{ item }} -o json"
  register: result
  until: "result.stdout.find('ip\":') != -1"
  retries: 30
  delay: 10

- name: Save ip as json
  set_fact:
    result_ip: "{{ result.stdout | from_json }}"

- name: Save public ip
  set_fact:
    ansible_ssh_host: "{{ result_ip.status.loadBalancer.ingress[0].ip }}"
    ansible_ssh_user: "{{ hostvars[item]['ansible_ssh_user']|default(provision_docker_ssh_user) }}"
    ansible_ssh_pass: "{{ hostvars[item]['ansible_ssh_pass']|default(provision_docker_ssh_pass) }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  changed_when: false

