---
- name: Delete existing service
  local_action:
    module: "shell kubectl delete service {{ item }}"
  failed_when: False

- name: Delete existing pod
  local_action:
    module: "shell kubectl delete pod {{ item }} --grace-period=1"
  failed_when: False
