- name: Stop and rm containers
  local_action: "shell docker rm --force {{ item }} || true"
  with_items: "{{ provision_docker_inventory_group }}"

- name: Bring up containers
  local_action: "shell docker run -d --name={{ item }} --privileged --expose=1-65535 {{ hostvars[item].image|default(provision_docker_image_default) }}"
  with_items: "{{ provision_docker_inventory_group }}"

- name: Get IP of container
  local_action:
    module: "shell"
    args: "{{ role_path }}/files/docker_inspect.sh {{ item }}"
  register: provision_docker_ip
  with_items: "{{ provision_docker_inventory_group }}"
  changed_when: false

- name: "Associate ip address with hosts"
  set_fact:
    ansible_ssh_host: "{{ provision_docker_ip.results[item.0].stdout }}"
    ansible_ssh_user: "{{ hostvars[item.1]['ansible_ssh_user']|default(provision_docker_ssh_user) }}"
    ansible_ssh_pass: "{{ hostvars[item.1]['ansible_ssh_pass']|default(provision_docker_ssh_pass) }}"
  delegate_to: "{{ item.1 }}"
  delegate_facts: True
  with_indexed_items: "{{ provision_docker_inventory_group }}"
  changed_when: false

- name: Wait for ssh
  wait_for:
    host: "{{ hostvars[item]['ansible_ssh_host'] }}"
    port: 22
    timeout: 30
    connect_timeout: 30
  with_items: "{{ provision_docker_inventory_group }}"

- name: Make sure ssh is really up
  ping:
  delegate_to: "{{ item }}"
  with_items: "{{ provision_docker_inventory_group }}"

