---
- name: Ensure old service has been deleted
  local_action:
    module: "shell kubectl delete service {{ item }}"
  failed_when: False
  register: result_service_deleted
  until: "result_service_deleted.rc == 1"
  retries: 30

- name: Ensure old pod has been deleted
  local_action:
    module: "shell kubectl delete pod {{ item }}"
  failed_when: False
  register: result_pod_deleted
  until: "result_pod_deleted.rc == 1"
  retries: 30

- name: Lay down pod description
  local_action:
    module: template
    src: pod.yml.j2
    dest: "{{ provision_docker_tmp_file }}"

- name: Bring up pod host
  local_action: 
    module: "shell kubectl create --filename={{ provision_docker_tmp_file }}"

- name: Expose public ip of pod
  local_action:
    module: "shell kubectl expose pods {{ item }} --type='LoadBalancer'"

- name: Find public ip
  local_action:
    module: "shell kubectl get services {{ item }} -o json"
  register: result
  until: "result.stdout.find('ip\":') != -1"
  retries: 30

- name: Save ip as json
  set_fact:
    result_ip: "{{ result.stdout | from_json }}"

- name: Save public ip
  set_fact:
    ansible_ssh_host: "{{ result_ip.status.loadBalancer.ingress[0].ip }}"
    ansible_ssh_user: "{{ hostvars[item]['ansible_ssh_user']|default(provision_docker_ssh_user) }}"
    ansible_ssh_pass: "{{ hostvars[item]['ansible_ssh_pass']|default(provision_docker_ssh_pass) }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  changed_when: false

