---
# Note: Ignore host key checking when using this module because it's common that docker contains will start with IP addresses that already have ssh signatures associated.

- include: inc_inventory_iface.yml
  when: "{{ provision_docker_inventory_group | length }} > 0"

- include: inc_cloud_iface.yml
  when: "{{ provision_docker_inventory | length }} > 0"

